### ISSUE TITLE
panic when decorate transport

### ISSUE THREAD

**Issue by xyluet** [opentracing-contrib/go-stdlib#59]
I wrapped a transport like below

```go
type tracingTransport struct {
	http.RoundTripper
	tracer opentracing.Tracer
}

func NewTracingTransport(rt http.RoundTripper, tracer opentracing.Tracer) http.RoundTripper {
	t := &tracingTransport{
		RoundTripper: rt,
		tracer:       tracer,
	}
	return t
}

func (t *tracingTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	rt := &nethttp.Transport{
		RoundTripper: t.RoundTripper,
	}
	req, ht := nethttp.TraceRequest(t.tracer, req)
	defer ht.Finish()

	return rt.RoundTrip(req)
}
```

and make a test:

```go
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {

	}))
	defer ts.Close()

	tracer := mocktracer.New()
	transport := client.NewTracingTransport(ts.Client().Transport, tracer)
	transport.RoundTrip(httptest.NewRequest("GET", ts.URL, nil))
```

and it panic 

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x755224]

goroutine 19 [running]:
testing.tRunner.func1.1(0x7bfb20, 0xb43430)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/testing/testing.go:988 +0x30d
testing.tRunner.func1(0xc0000d4480)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/testing/testing.go:991 +0x3f9
panic(0x7bfb20, 0xb43430)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/runtime/panic.go:969 +0x166
github.com/opentracing/opentracing-go/ext.stringTagName.Set(...)
	/home/ali/.asdf/installs/golang/1.14.7/packages/pkg/mod/github.com/opentracing/opentracing-go@v1.1.0/ext/tags.go:170
github.com/opentracing-contrib/go-stdlib/nethttp.(*Tracer).getConn(0xc0000de8c0, 0xc0000a6440, 0xf)
	/home/ali/.asdf/installs/golang/1.14.7/packages/pkg/mod/github.com/opentracing-contrib/go-stdlib@v1.0.0/nethttp/client.go:269 +0x84
reflect.Value.call(0x79bc80, 0xc0000f8180, 0x193, 0x8292e9, 0x4, 0xc0000b8560, 0x1, 0x1, 0x0, 0x0, ...)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x79bc80, 0xc0000f8180, 0x193, 0xc0000b8560, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/reflect/value.go:321 +0xb4
net/http/httptrace.(*ClientTrace).compose.func1(0xc0000b8560, 0x1, 0x1, 0xc0000b8560, 0x110, 0x7f11c0)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/net/http/httptrace/trace.go:204 +0xa5
reflect.callReflect(0xc00009f1a0, 0xc000107830, 0xc000107818)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/reflect/value.go:549 +0x322
reflect.makeFuncStub(0xc0000a6440, 0xf, 0xd0, 0x7f0d40, 0xb51780, 0x7f3b8a8e47d0, 0x0, 0xd0, 0xc0000a1d40, 0x30, ...)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/reflect/asm_amd64.s:20 +0x42
net/http.(*Transport).getConn(0xc0000e43c0, 0xc00009fa40, 0x0, 0xc0000a8124, 0x4, 0xc0000a6440, 0xf, 0x0, 0x0, 0x0, ...)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/net/http/transport.go:1252 +0xe6
net/http.(*Transport).roundTrip(0xc0000e43c0, 0xc000120200, 0x0, 0x79bfc0, 0xb11282)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/net/http/transport.go:552 +0x726
net/http.(*Transport).RoundTrip(0xc0000e43c0, 0xc000120200, 0xc0000b84e0, 0x79bfc0, 0xb11282)
	/home/ali/.asdf/installs/golang/1.14.7/go/src/net/http/roundtrip.go:17 +0x35
github.com/opentracing-contrib/go-stdlib/nethttp.(*Transport).RoundTrip(0xc000056eb8, 0xc000120200, 0xc000120100, 0x0, 0x0)
	/home/ali/.asdf/installs/golang/1.14.7/packages/pkg/mod/github.com/opentracing-contrib/go-stdlib@v1.0.0/nethttp/client.go:184 +0x256
```

I did wrong or something?

**Comment by xyluet** [comment]
never mind, i found it why
